name: OWASP Dependency Check

on:
  schedule:  # UTC
  - cron:  '0 0 * * *'

jobs:
  owasp_dependency_check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.4.0
        with:
          ref: master

      # https://github.com/stevespringett/nist-data-mirror
      - name: Run NIST Data Mirror
        run: |
          if [ ! -d /home/runner/cache/target/docs ]; then mkdir -p /home/runner/cache/target/docs; fi
          chmod 777 /home/runner/cache/target/docs

          # needed for enable local PC execution
          CACHE_DIR=/tmp/cache
          mkdir -p ${CACHE_DIR}/target/docs

          docker run --rm -d \
            --name mirror \
            -p 8080:80 \
            --mount type=bind,source=/home/runner/cache/target/docs/,target=/usr/local/apache2/htdocs \
            sspringett/nvdmirror
          sleep 120s
          docker logs mirror
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: OWASP dependency check
        run: |
          set +e
          ERRORS="$(./mvnw -q dependency-check:check)"
          RESULT=$?
          if [ ${RESULT} -ne 0 ]; then echo "::error::${ERRORS}"; fi
          exit ${RESULT}

      - name: Stop NIST Data Mirror
        if: always()
        run: |
          set +e
          docker stop mirror
