name: OWASP Dependency Check

on:
  schedule:  # UTC
  - cron:  '0 0 * * *'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.4
        with:
          ref: master

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: OWASP dependency check
        id: run_owasp_dependency_check
        run: |
          ./mvnw dependency-check:check
