name: Unit Test

on:
  schedule:  # UTC
  - cron:  '0 0 * * *'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.5
        with:
          ref: develop

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Test
        id: run_test
        run: |
          ./mvnw test
