name: Unit Test

on: [push]
  # schedule:  # UTC
  # - cron:  '30 16,22 * * *'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Test
        id: run_test
        run: |
          ./mvnw test

      - name: OWASP dependency check
        id: run_owasp_dependency_check
        run: |
          ./mvnw dependency-check:check
